const nodemailer = require('nodemailer');

const sendEmail = (visitor, employee, timeOfVisit) => {
  const [visitorName, visitorEmail] = visitor;
  const [employeeName, employeeEmail] = employee;

  const transporter = nodemailer.createTransport({
    host: process.env.BREVO_SMTP,
    port: process.env.BREVO_PORT,
    secure: false,
    auth: {
      user: process.env.BREVO_LOGIN,
      pass: process.env.BREVO_PASSWORD,
    },
    tls: {
      ciphers: 'SSLv3',
    },
  });

  const meetingTime = new Date(`${timeOfVisit}`).toUTCString().slice(0, 22);

  const notificationContent = `
    <div>
      <p>Hello there 👋🏾,</p>
      <br />
      <b><em>Scheduling Completed Successfully.</em></b>
      <br />
      <br />
      <p>${visitorName} will be meeting ${employeeName} at ${meetingTime} WAT.</p>
      <br />
      <br />
      <br />
      <h6>Automatically generated by the Mandilas visitor management system.</h6>
    </div>
  `;

  const message = async () => {
    const info = await transporter.sendMail({
      from: process.env.BREVO_SENDER,
      to: `${visitorEmail}, ${employeeEmail}`, // list of receivers separated by commas
      subject: 'Meeting Scheduled with Mandilas Employee',
      html: notificationContent, // html email body
    });

    console.log('Message sent: %s', info.messageId);
  };

  message().catch(console.error);
};

module.exports = sendEmail;
